#!/bin/bash

nro_proc=`grep Nro_clientes ambiente.in | cut -d " " -f 2`

make clean > /dev/null
make > /dev/null
java -cp .:/usr/local/rabbitmq-jar/amqp-client-4.0.2.jar:/usr/local/rabbitmq-jar/slf4j-api-1.7.21.jar:/usr/local/rabbitmq-jar/slf4j-simple-1.7.22.jar Recv & 
for i in `seq 1 $nro_proc`
do
    sleep 1
    pos=`expr $i + 1`;
    nom_maquinas=`grep Maquinas ambiente.in | cut -d " " -f $pos`
    px=`grep Processos ambiente.in | cut -d " " -f $pos`
    scp *.class $nom_maquinas: > /dev/null
    scp stdin0 $nom_maquinas: > /dev/null
    #echo 'ssh' $nom_maquinas 'java' $px ens1 $i
    ssh $nom_maquinas java -cp .:/usr/local/rabbitmq-jar/amqp-client-4.0.2.jar:/usr/local/rabbitmq-jar/slf4j-api-1.7.21.jar:/usr/local/rabbitmq-jar/slf4j-simple-1.7.22.jar $px ens1 $i 
    #java $px ens1 $i < stdin0 
    #echo 'ssh' $nom_maquinas 'rm -f' $px'.class'
    ssh $nom_maquinas rm -f *.class >/dev/null
    ssh $nom_maquinas rm -f stdin0 >/dev/null
done
